data = [
    {'name': 'Instagram', 'follower_count': 346, 'description': 'Social media platform', 'country': 'United States'},
    {'name': 'Cristiano Ronaldo', 'follower_count': 215, 'description': 'Footballer', 'country': 'Portugal'},
    {'name': 'Dwayne Johnson', 'follower_count': 320, 'description': 'Actor and wrestler', 'country': 'United States'},
    {'name': 'Kylie Jenner', 'follower_count': 280, 'description': 'Entrepreneur and model', 'country': 'United States'},
    {'name': 'Ariana Grande', 'follower_count': 250, 'description': 'Singer and actress', 'country': 'United States'},
    {'name': 'Selena Gomez', 'follower_count': 240, 'description': 'Singer and actress', 'country': 'United States'},
    {'name': 'Lionel Messi', 'follower_count': 230, 'description': 'Footballer', 'country': 'Argentina'},
    {'name': 'Kim Kardashian', 'follower_count': 210, 'description': 'Entrepreneur and TV personality', 'country': 'United States'},
    {'name': 'Beyoncé', 'follower_count': 200, 'description': 'Singer and actress', 'country': 'United States'},
    {'name': 'Taylor Swift', 'follower_count': 180, 'description': 'Singer and songwriter', 'country': 'United States'},
    {'name': 'National Geographic', 'follower_count': 170, 'description': 'Magazine and media organization', 'country': 'United States'},
    {'name': 'Justin Bieber', 'follower_count': 160, 'description': 'Singer and songwriter', 'country': 'Canada'},
    {'name': 'Kendall Jenner', 'follower_count': 150, 'description': 'Model and entrepreneur', 'country': 'United States'},
    {'name': 'Neymar', 'follower_count': 140, 'description': 'Footballer', 'country': 'Brazil'},
    {'name': 'Nike', 'follower_count': 130, 'description': 'Sportswear brand', 'country': 'United States'},
    {'name': 'Jennifer Lopez', 'follower_count': 120, 'description': 'Singer and actress', 'country': 'United States'},
    {'name': 'Billie Eilish', 'follower_count': 115, 'description': 'Singer and songwriter', 'country': 'United States'},
    {'name': 'Shakira', 'follower_count': 110, 'description': 'Singer and songwriter', 'country': 'Colombia'},
    {'name': 'Virat Kohli', 'follower_count': 105, 'description': 'Cricketer', 'country': 'India'},
    {'name': 'Chris Hemsworth', 'follower_count': 100, 'description': 'Actor', 'country': 'Australia'},
    {'name': 'Emma Watson', 'follower_count': 95, 'description': 'Actress and activist', 'country': 'United Kingdom'},
    {'name': 'The Rock', 'follower_count': 90, 'description': 'Actor and wrestler', 'country': 'United States'},
    {'name': 'Zendaya', 'follower_count': 85, 'description': 'Actress and singer', 'country': 'United States'},
    {'name': 'Priyanka Chopra', 'follower_count': 80, 'description': 'Actress and producer', 'country': 'India'},
    {'name': 'Lady Gaga', 'follower_count': 75, 'description': 'Singer and actress', 'country': 'United States'},
    {'name': 'Ed Sheeran', 'follower_count': 70, 'description': 'Singer and songwriter', 'country': 'United Kingdom'},
    {'name': 'Shawn Mendes', 'follower_count': 65, 'description': 'Singer and songwriter', 'country': 'Canada'},
    {'name': 'NASA', 'follower_count': 60, 'description': 'Space exploration agency', 'country': 'United States'},
    {'name': 'Barack Obama', 'follower_count': 58, 'description': 'Former President', 'country': 'United States'},
    {'name': 'Elon Musk', 'follower_count': 55, 'description': 'Entrepreneur and CEO', 'country': 'United States'},
    {'name': 'Cristiano Ronaldo Jr.', 'follower_count': 53, 'description': 'Footballer\'s son', 'country': 'Portugal'},
    {'name': 'PewDiePie', 'follower_count': 52, 'description': 'YouTuber', 'country': 'Sweden'},
    {'name': 'LeBron James', 'follower_count': 50, 'description': 'Basketball player', 'country': 'United States'},
    {'name': 'Adidas', 'follower_count': 48, 'description': 'Sportswear brand', 'country': 'Germany'},
    {'name': 'Rihanna', 'follower_count': 45, 'description': 'Singer and entrepreneur', 'country': 'Barbados'},
    {'name': 'Drake', 'follower_count': 42, 'description': 'Rapper and singer', 'country': 'Canada'},
    {'name': 'Will Smith', 'follower_count': 40, 'description': 'Actor', 'country': 'United States'},
    {'name': 'Bruno Mars', 'follower_count': 38, 'description': 'Singer and songwriter', 'country': 'United States'},
    {'name': 'Harry Styles', 'follower_count': 35, 'description': 'Singer and actor', 'country': 'United Kingdom'},
    {'name': 'Tom Holland', 'follower_count': 33, 'description': 'Actor', 'country': 'United Kingdom'},
    {'name': 'Selena Gomez Fan Page', 'follower_count': 30, 'description': 'Fan page', 'country': 'Worldwide'},
    {'name': 'Marvel Studios', 'follower_count': 28, 'description': 'Film studio', 'country': 'United States'},
    {'name': 'DC Comics', 'follower_count': 25, 'description': 'Comic and film studio', 'country': 'United States'},
    {'name': 'Friends TV', 'follower_count': 22, 'description': 'TV show fan page', 'country': 'Worldwide'},
    {'name': 'The Simpsons', 'follower_count': 20, 'description': 'TV show', 'country': 'United States'},
    {'name': 'Spotify', 'follower_count': 18, 'description': 'Music streaming platform', 'country': 'Sweden'},
    {'name': 'Netflix', 'follower_count': 15, 'description': 'Streaming service', 'country': 'United States'},
    {'name': 'Coca-Cola', 'follower_count': 12, 'description': 'Beverage brand', 'country': 'United States'},
    {'name': 'BMW', 'follower_count': 10, 'description': 'Automobile brand', 'country': 'Germany'},
    # Repeat the pattern to reach 100 entries...
]
